import Link from "next/link";
import { Archive, ArrowUpRight, CalendarDays, CircleAlert, FileLock2, Landmark, PackageOpen, ShieldCheck, UsersRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { HouseholdSetupForm } from "@/components/household-setup-form";
import { HouseholdSelector } from "@/components/household-selector";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import type { DashboardSummary } from "@/lib/dashboard/summary";
import { dashboardStateCopy } from "@/lib/dashboard/state";

const modules = [
  { title: "Family", caption: "Profiles & members", icon: UsersRound, href: "/family" },
  { title: "Schedule", caption: "Events & care", icon: CalendarDays, href: "/schedule" },
  { title: "Finance", caption: "Bills & records", icon: Landmark, href: "/finance" },
  { title: "Assets", caption: "Home & valuables", icon: PackageOpen, href: "/assets" },
  { title: "Documents", caption: "Private vault", icon: FileLock2, href: "/documents" },
  { title: "Reminders", caption: "Due obligations", icon: Archive, href: "/reminders" },
];

export function DashboardWorkspace({ userEmail, configured, summary }: { userEmail?: string | null; configured: boolean; summary: DashboardSummary }) {
  const stateCopy = dashboardStateCopy(summary, configured);
  return (
    <main className="mx-auto w-full max-w-6xl px-4 pb-32 pt-5 sm:px-6 sm:pb-10 lg:px-8">
      <section className="relative overflow-hidden border border-contrast bg-contrast p-5 text-white shadow-tactile sm:p-7"><div className="absolute -right-10 -top-12 h-44 w-44 border-[18px] border-white/20" aria-hidden="true" /><div className="absolute bottom-0 right-[12%] h-10 w-32 bg-brand/40" aria-hidden="true" /><div className="relative"><div className="flex flex-wrap items-center justify-between gap-3"><div><Badge className="border-white/60 bg-white text-contrast">Household snapshot</Badge><p className="mt-3 font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-white/65">Secure · household scoped · UTC-ready</p></div><span className="inline-flex items-center gap-2 font-mono text-[10px] font-bold uppercase tracking-[0.13em] text-white/75"><ShieldCheck className="size-4" aria-hidden="true" />Protected</span></div><h1 className="mt-4 max-w-2xl text-4xl font-black uppercase leading-[0.9] tracking-[-0.07em] sm:text-6xl">{summary.householdName ? `${summary.householdName}.` : "Your family, clearly organized."}</h1><p className="mt-3 max-w-xl text-sm leading-6 text-white/70">{userEmail ? `Signed in as ${userEmail}. ` : ""}Review what needs attention, then move into the right household workspace.</p></div></section>
      <section className="grid gap-3 py-4 sm:grid-cols-2 lg:grid-cols-4" aria-label="Household snapshot"><StatusBlock label="Recorded spend" value={formatCurrency(summary.totalExpenses, summary.currency)} note="Active household expense entries." tone="dark" /><StatusBlock label="Needs attention" value={String(summary.reminderCount)} note="Open reminders and due obligations." highlight={summary.reminderCount > 0} /><StatusBlock label="Next events" value={String(summary.upcomingEvents.length)} note="Upcoming household commitments." /><StatusBlock label="Private vault" value={String(summary.documentCount)} note="Protected documents on record." /></section>
      {stateCopy ? <section className="mb-5 border border-dashed border-brand bg-soft p-4 sm:p-5" aria-live="polite"><p className="font-mono text-[11px] font-bold uppercase tracking-[0.14em] text-ink">{stateCopy.title}</p><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">{stateCopy.body}</p>{stateCopy.showOnboarding && userEmail ? <HouseholdSetupForm /> : null}</section> : null}
      {summary.status === "ready" ? <HouseholdSelector households={summary.availableHouseholds} activeHouseholdId={summary.activeHouseholdId} /> : null}
      <section className="grid gap-4 lg:grid-cols-[1.4fr_0.9fr]" aria-label="Priority household actions"><Card><CardHeader><p className="font-mono text-[10px] font-bold uppercase tracking-[0.15em] text-brand">Attention center</p><h2 className="mt-1 text-xl font-black uppercase tracking-[-0.05em]">What needs action</h2></CardHeader><CardContent>{summary.dueReminders.length > 0 ? <div className="space-y-2">{summary.dueReminders.map((reminder) => <RecordLine key={reminder.id} title={`${reminder.kind} · ${reminder.title}`} detail={`Due ${new Date(reminder.due_at).toLocaleString()}`} />)}</div> : <EmptyLine label="No urgent reminders" detail="Bills, renewals, appointments, and birthdays will appear here when they need attention." />}</CardContent></Card><section className="border border-line bg-soft p-4 shadow-tactile sm:p-5"><div className="flex items-center gap-2 text-brand"><CircleAlert className="size-4" aria-hidden="true" /><p className="font-mono text-[10px] font-bold uppercase tracking-[0.15em]">Quick actions</p></div><div className="mt-4 grid gap-2">{modules.slice(0, 3).map((module) => { const Icon = module.icon; return <Link key={module.title} href={module.href} className="group flex min-h-14 items-center gap-3 border border-line bg-surface px-3 transition hover:border-brand hover:text-brand"><span className="grid size-9 place-items-center bg-brand text-white"><Icon className="size-4" aria-hidden="true" /></span><span className="min-w-0 flex-1"><span className="block font-semibold">Open {module.title}</span><span className="block text-xs text-muted">{module.caption}</span></span><ArrowUpRight className="size-4 text-muted group-hover:text-brand" aria-hidden="true" /></Link>; })}</div></section></section>
      <section className="mt-5" aria-labelledby="modules-heading"><div className="mb-3 flex items-end justify-between gap-4"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-muted">All workspaces</p><h2 id="modules-heading" className="mt-1 text-2xl font-black uppercase tracking-[-0.055em]">Manage your household</h2></div><span className="hidden font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-muted sm:block">Tap to continue</span></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{modules.map((module, index) => { const Icon = module.icon; return <Link key={module.title} href={module.href} className={index % 2 === 1 ? "group block min-h-40 border border-line bg-soft p-4 shadow-tactile-sm transition hover:-translate-y-0.5 hover:border-brand hover:shadow-tactile" : "group block min-h-40 border border-line bg-surface p-4 shadow-tactile-sm transition hover:-translate-y-0.5 hover:border-brand hover:shadow-tactile"}><div className="flex items-start justify-between gap-4"><span className="grid size-10 place-items-center border border-brand bg-brand text-white"><Icon className="size-4" strokeWidth={2.2} /></span><ArrowUpRight className="size-4 text-muted transition group-hover:text-brand" aria-hidden="true" /></div><h3 className="mt-7 text-xl font-black uppercase tracking-[-0.055em]">{module.title}</h3><p className="mt-1 font-mono text-[10px] font-bold uppercase tracking-[0.13em] text-muted">{module.caption}</p></Link>; })}</div></section>
      <section className="mt-5 grid gap-4 lg:grid-cols-2"><Card id="schedule"><CardHeader><p className="font-mono text-[10px] font-bold uppercase tracking-[0.15em] text-muted">Timeline</p><h2 className="mt-1 text-xl font-black uppercase tracking-[-0.05em]">Upcoming activity</h2></CardHeader><CardContent>{summary.upcomingEvents.length > 0 ? <div className="space-y-2">{summary.upcomingEvents.map((event) => <RecordLine key={event.id} title={event.title} detail={new Date(event.starts_at).toLocaleString()} />)}</div> : <EmptyLine label="No scheduled items yet" detail="Appointments, birthday dates and renewals will appear here." />}</CardContent></Card><Card id="documents" className="bg-soft"><CardHeader><p className="font-mono text-[10px] font-bold uppercase tracking-[0.15em] text-muted">Recent changes</p><h2 className="mt-1 text-xl font-black uppercase tracking-[-0.05em]">Activity history</h2></CardHeader><CardContent>{summary.recentActivity.length > 0 ? <div className="space-y-2">{summary.recentActivity.map((activity) => <RecordLine key={activity.id} title={activity.action.replace(":", " · ")} detail={new Date(activity.occurred_at).toLocaleString()} />)}</div> : <EmptyLine label="No recent activity yet" detail="Authorized changes to household records will appear here." />}</CardContent></Card></section>
    </main>
  );
}

function StatusBlock({ label, value, note, tone = "light", highlight = false }: { label: string; value: string; note: string; tone?: "light" | "dark"; highlight?: boolean }) { return <div className={tone === "dark" ? "border border-contrast bg-contrast p-4 text-white shadow-tactile-sm" : highlight ? "border border-brand bg-surface p-4 shadow-tactile-sm" : "border border-line bg-surface p-4 shadow-tactile-sm"}><p className={tone === "dark" ? "font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-white/65" : "font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-muted"}>{label}</p><p className="mt-3 text-4xl font-black tracking-[-0.08em]">{value}</p><p className={tone === "dark" ? "mt-2 text-xs leading-5 text-white/65" : "mt-2 text-xs leading-5 text-muted"}>{note}</p></div>; }
function EmptyLine({ label, detail }: { label: string; detail: string }) { return <div className="flex min-h-28 flex-col justify-end border-l-4 border-brand bg-canvas p-4"><p className="font-semibold text-ink">{label}</p><p className="mt-1 text-sm leading-6 text-muted">{detail}</p></div>; }
function RecordLine({ title, detail }: { title: string; detail: string }) { return <div className="border-l-4 border-brand bg-canvas p-3"><p className="font-semibold text-sm text-ink">{title}</p><p className="mt-1 font-mono text-[10px] uppercase tracking-[0.1em] text-muted">{detail}</p></div>; }
function formatCurrency(value: number, currency = "USD") { return new Intl.NumberFormat("en", { style: "currency", currency, maximumFractionDigits: 0 }).format(value); }
