import Link from "next/link";
import { Archive, ArrowUpRight, CalendarDays, FileLock2, Landmark, PackageOpen, UsersRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { HouseholdSetupForm } from "@/components/household-setup-form";
import { HouseholdSelector } from "@/components/household-selector";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import type { DashboardSummary } from "@/lib/dashboard/summary";
import { dashboardStateCopy } from "@/lib/dashboard/state";

const modules = [
  { title: "Family", caption: "Profiles & members", icon: UsersRound, href: "/family" },
  { title: "Schedule", caption: "Events & care", icon: CalendarDays, href: "/schedule" },
  { title: "Finance", caption: "Bills & records", icon: Landmark, href: "/finance" },
  { title: "Assets", caption: "Home & valuables", icon: PackageOpen, href: "/assets" },
  { title: "Documents", caption: "Private vault", icon: FileLock2, href: "/documents" },
  { title: "Reminders", caption: "Due obligations", icon: Archive, href: "/reminders" },
];

export function DashboardWorkspace({ userEmail, configured, summary }: { userEmail?: string | null; configured: boolean; summary: DashboardSummary }) {
  const stateCopy = dashboardStateCopy(summary, configured);
  return (
    <main className="mx-auto w-full max-w-6xl px-4 pb-28 pt-5 sm:px-6 lg:px-8">
      <section className="relative overflow-hidden border border-ink bg-ink p-5 text-canvas shadow-tactile sm:p-7">
        <div className="absolute -right-10 -top-12 h-44 w-44 border-[18px] border-muted/40" aria-hidden="true" /><div className="absolute bottom-0 left-[42%] h-10 w-32 bg-muted/30" aria-hidden="true" />
        <div className="relative max-w-3xl"><div className="mb-5 flex flex-wrap items-center gap-2"><Badge className="border-canvas/60 bg-canvas text-ink">Private workspace</Badge><span className="font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-canvas/65">UTC-ready · RLS-ready</span></div><p className="font-mono text-[11px] font-bold uppercase tracking-[0.18em] text-canvas/70">Good to have you here{userEmail ? `, ${userEmail}` : ""}</p><h1 className="mt-3 max-w-2xl text-4xl font-black uppercase leading-[0.88] tracking-[-0.075em] sm:text-6xl">{summary.householdName ? `${summary.householdName}.` : "One operational home for your family."}</h1></div>
      </section>
      <section className="grid gap-3 py-4 sm:grid-cols-4" aria-label="Workspace status"><StatusBlock label="Upcoming events" value={String(summary.upcomingEvents.length)} note="Your next five household events." /><StatusBlock label="Open reminders" value={String(summary.reminderCount)} note="Bills, renewals, care and birthdays." tone="dark" /><StatusBlock label="Vault documents" value={String(summary.documentCount)} note="Private documents linked to your household." /><StatusBlock label="Expenses" value={formatCurrency(summary.totalExpenses, summary.currency)} note="All active expense records." tone="dark" /></section>
      {stateCopy ? <section className="mb-5 border border-dashed border-ink bg-soft p-4 sm:p-5" aria-live="polite"><p className="font-mono text-[11px] font-bold uppercase tracking-[0.14em] text-ink">{stateCopy.title}</p><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">{stateCopy.body}</p>{stateCopy.showOnboarding && userEmail ? <HouseholdSetupForm /> : null}</section> : null}
      {summary.status === "ready" ? <HouseholdSelector households={summary.availableHouseholds} activeHouseholdId={summary.activeHouseholdId} /> : null}
      <section aria-labelledby="modules-heading"><div className="mb-3 flex items-end justify-between gap-4"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-muted">Control surface</p><h2 id="modules-heading" className="mt-1 text-2xl font-black uppercase tracking-[-0.055em]">Family modules</h2></div><span className="font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-muted">Foundation mode</span></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{modules.map((module, index) => { const Icon = module.icon; return <Link key={module.title} href={module.href} className={index % 2 === 1 ? "group block border border-ink bg-soft p-4 shadow-tactile-sm transition hover:-translate-y-0.5 hover:shadow-tactile" : "group block border border-ink bg-surface p-4 shadow-tactile-sm transition hover:-translate-y-0.5 hover:shadow-tactile"}><div className="flex items-start justify-between gap-4"><span className="grid size-10 place-items-center border border-ink bg-ink text-canvas"><Icon className="size-4" strokeWidth={2.2} /></span><ArrowUpRight className="size-4 text-muted transition group-hover:text-ink" aria-hidden="true" /></div><h3 className="mt-8 text-xl font-black uppercase tracking-[-0.055em]">{module.title}</h3><p className="mt-1 font-mono text-[10px] font-bold uppercase tracking-[0.13em] text-muted">{module.caption}</p></Link>; })}</div></section>
      <section className="mt-5 grid gap-4 lg:grid-cols-3"><Card id="schedule"><CardHeader><p className="font-mono text-[10px] font-bold uppercase tracking-[0.15em] text-muted">Timeline</p><h2 className="mt-1 text-xl font-black uppercase tracking-[-0.05em]">Upcoming activity</h2></CardHeader><CardContent>{summary.upcomingEvents.length > 0 ? <div className="space-y-2">{summary.upcomingEvents.map((event) => <RecordLine key={event.id} title={event.title} detail={new Date(event.starts_at).toLocaleString()} />)}</div> : <EmptyLine label="No scheduled items yet" detail="Appointments, birthday dates and renewals will appear here." />}</CardContent></Card><Card className="bg-soft"><CardHeader><p className="font-mono text-[10px] font-bold uppercase tracking-[0.15em] text-muted">Due in seven days</p><h2 className="mt-1 text-xl font-black uppercase tracking-[-0.05em]">Timely reminders</h2></CardHeader><CardContent>{summary.dueReminders.length > 0 ? <div className="space-y-2">{summary.dueReminders.map((reminder) => <RecordLine key={reminder.id} title={`${reminder.kind} · ${reminder.title}`} detail={new Date(reminder.due_at).toLocaleString()} />)}</div> : <EmptyLine label="No urgent reminders" detail="Create a bill, renewal, appointment, birthday, or custom reminder." />}</CardContent></Card><Card id="documents" className="bg-soft"><CardHeader><p className="font-mono text-[10px] font-bold uppercase tracking-[0.15em] text-muted">Recent changes</p><h2 className="mt-1 text-xl font-black uppercase tracking-[-0.05em]">Activity history</h2></CardHeader><CardContent>{summary.recentActivity.length > 0 ? <div className="space-y-2">{summary.recentActivity.map((activity) => <RecordLine key={activity.id} title={activity.action.replace(":", " · ")} detail={new Date(activity.occurred_at).toLocaleString()} />)}</div> : <EmptyLine label="No recent activity yet" detail="Authorized changes to household records will appear here." />}</CardContent></Card></section>
    </main>
  );
}

function StatusBlock({ label, value, note, tone = "light" }: { label: string; value: string; note: string; tone?: "light" | "dark" }) { return <div className={tone === "dark" ? "border border-ink bg-ink p-4 text-canvas shadow-tactile-sm" : "border border-line bg-surface p-4 shadow-tactile-sm"}><p className={tone === "dark" ? "font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-canvas/65" : "font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-muted"}>{label}</p><p className="mt-3 text-4xl font-black tracking-[-0.08em]">{value}</p><p className={tone === "dark" ? "mt-2 text-xs leading-5 text-canvas/65" : "mt-2 text-xs leading-5 text-muted"}>{note}</p></div>; }
function EmptyLine({ label, detail }: { label: string; detail: string }) { return <div className="flex min-h-28 flex-col justify-end border-l-4 border-ink bg-canvas p-4"><p className="font-semibold text-ink">{label}</p><p className="mt-1 text-sm leading-6 text-muted">{detail}</p></div>; }
function RecordLine({ title, detail }: { title: string; detail: string }) { return <div className="border-l-4 border-ink bg-canvas p-3"><p className="font-semibold text-sm text-ink">{title}</p><p className="mt-1 font-mono text-[10px] uppercase tracking-[0.1em] text-muted">{detail}</p></div>; }
function formatCurrency(value: number, currency = "USD") { return new Intl.NumberFormat("en", { style: "currency", currency, maximumFractionDigits: 0 }).format(value); }
