"use client";

import { useActionState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { createAsset, createFamilyPerson, createFinancialRecord, createInvitation, createReminder, createScheduleItem, initialModuleActionState, uploadDocument, type ModuleActionState } from "@/app/(workspace)/module-actions";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { FamilyAccessPanel, type HouseholdMemberView } from "@/components/family-access-panel";

export type ModuleKey = "family" | "finance" | "assets" | "schedule" | "documents" | "reminders";
type RecordRow = Record<string, unknown>;

const moduleMeta: Record<ModuleKey, { eyebrow: string; title: string; description: string }> = {
  family: { eyebrow: "People & membership", title: "Family records", description: "Keep profiles, relationships, and private membership operations in one household-scoped workspace." },
  finance: { eyebrow: "Income & expenses", title: "Financial records", description: "Log the household money movement that matters, with RLS-protected access." },
  assets: { eyebrow: "Home & valuables", title: "Assets", description: "Track household assets, values, and renewal points without exposing data outside the household." },
  schedule: { eyebrow: "Events & care", title: "Schedule", description: "Maintain appointments, care events, and household commitments in local time." },
  documents: { eyebrow: "Private storage", title: "Document vault", description: "Upload supported files to the private family bucket and retain searchable metadata." },
  reminders: { eyebrow: "Obligations", title: "Reminders", description: "Capture bills, renewals, appointments, birthdays, and other timely household obligations." },
};

export function ModuleWorkspace({ module, householdName, records, members = [], actorRole = "limited", searchQuery = "" }: { module: ModuleKey; householdName: string; records: RecordRow[]; members?: HouseholdMemberView[]; actorRole?: "owner" | "adult" | "limited"; searchQuery?: string }) {
  const meta = moduleMeta[module];
  return (
    <main className="container py-7 sm:py-10">
      <div className="border border-contrast bg-contrast p-5 text-white shadow-tactile sm:p-7"><p className="font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-white/65">{householdName} · {meta.eyebrow}</p><h1 className="mt-3 text-4xl font-black uppercase leading-[0.88] tracking-[-0.07em] sm:text-6xl">{meta.title}</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-white/70">{meta.description}</p></div>
      <section className="mt-5 grid gap-5 lg:grid-cols-[0.85fr_1.15fr]"><Card><CardHeader><p className="font-mono text-[10px] font-bold uppercase tracking-[0.15em] text-muted">New record</p><h2 className="mt-1 text-xl font-black uppercase tracking-[-0.05em]">Add to workspace</h2></CardHeader><CardContent><ModuleForm module={module} /></CardContent></Card><Card className="bg-soft"><CardHeader><p className="font-mono text-[10px] font-bold uppercase tracking-[0.15em] text-muted">Household data</p><h2 className="mt-1 text-xl font-black uppercase tracking-[-0.05em]">Recent records</h2></CardHeader><CardContent>{module === "documents" ? <DocumentSearch initialQuery={searchQuery} /> : null}<RecordList module={module} records={records} /></CardContent></Card></section>{module === "family" ? <FamilyAccessPanel members={members} actorRole={actorRole} /> : null}
    </main>
  );
}

function ModuleForm({ module }: { module: ModuleKey }) {
  const action = module === "family" ? createFamilyPerson : module === "finance" ? createFinancialRecord : module === "assets" ? createAsset : module === "schedule" ? createScheduleItem : module === "documents" ? uploadDocument : createReminder;
  const [state, formAction, pending] = useActionState(action, initialModuleActionState);
  const router = useRouter();
  useEffect(() => { if (state.status === "success") router.refresh(); }, [router, state.status]);
  return <form action={formAction} className="grid gap-3" encType={module === "documents" ? "multipart/form-data" : undefined}>{module === "family" ? <FamilyFields /> : module === "finance" ? <FinanceFields /> : module === "assets" ? <AssetFields /> : module === "schedule" ? <ScheduleFields /> : module === "documents" ? <DocumentFields /> : <ReminderFields />}<ActionNotice state={state} /><Button type="submit" size="touch" disabled={pending}>{pending ? "Saving" : module === "documents" ? "Upload private file" : "Save record"}</Button></form>;
}

function Label({ name, children }: { name: string; children: React.ReactNode }) { return <label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">{children}</span><Input name={name} required /></label>; }
function FamilyFields() { return <><Label name="displayName">Name</Label><Label name="relationship">Relationship</Label><label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">Birth date</span><Input name="birthDate" type="date" /></label></>; }
function FinanceFields() { return <><label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">Record type</span><select name="kind" className="h-11 border border-line bg-canvas px-3 text-sm outline-none focus:border-brand focus:ring-2 focus:ring-brand/25"><option value="expense">Expense</option><option value="income">Income</option><option value="transfer">Transfer</option><option value="liability">Liability</option></select></label><Label name="title">Title</Label><div className="grid grid-cols-2 gap-3"><Label name="amount">Amount</Label><Label name="currency">Currency</Label></div><label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">Date</span><Input name="occurredOn" type="date" required /></label><Label name="category">Category</Label></>; }
function AssetFields() { return <><Label name="name">Asset name</Label><Label name="category">Category</Label><div className="grid grid-cols-2 gap-3"><Label name="estimatedValue">Estimated value</Label><Label name="currency">Currency</Label></div><label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">Renewal date</span><Input name="renewalDueAt" type="datetime-local" /></label></>; }
function ScheduleFields() { return <><Label name="title">Event title</Label><Label name="category">Category</Label><label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">Starts</span><Input name="startsAt" type="datetime-local" required /></label><label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">Ends</span><Input name="endsAt" type="datetime-local" /></label></>; }
function DocumentFields() { return <><label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">File</span><Input name="file" type="file" accept="application/pdf,image/jpeg,image/png,text/plain" required /></label><Label name="label">Label</Label><Label name="relatedType">Related record type (optional)</Label><Label name="relatedId">Related record ID (optional)</Label><p className="text-xs leading-5 text-muted">PDF, JPEG, PNG, or text file; maximum 50 MB. File bytes stay in the private family bucket, while metadata is searchable and may link to a family record.</p></>; }
function ReminderFields() { return <><label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">Reminder type</span><select name="kind" className="h-11 border border-line bg-canvas px-3 text-sm outline-none focus:border-brand focus:ring-2 focus:ring-brand/25"><option value="bill">Bill</option><option value="renewal">Renewal</option><option value="appointment">Appointment</option><option value="birthday">Birthday</option><option value="custom">Custom</option></select></label><Label name="title">Title</Label><label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">Due</span><Input name="dueAt" type="datetime-local" required /></label><Label name="leadTimeMinutes">Lead time in minutes</Label></>; }
function ActionNotice({ state }: { state: ModuleActionState }) { return state.status === "idle" ? null : <p role="status" className={state.status === "error" ? "text-sm font-medium text-error" : "text-sm font-medium text-ink"}>{state.message}{state.shareCode ? <><br /><code className="mt-2 inline-block select-all border border-line bg-soft px-2 py-1 text-xs text-ink">{state.shareCode}</code></> : null}</p>; }
function DocumentSearch({ initialQuery }: { initialQuery: string }) { return <form action="/documents" className="mb-4 flex gap-2"><Input name="q" defaultValue={initialQuery} placeholder="Search file name or label" aria-label="Search private documents" /><Button type="submit" size="compact">Search</Button></form>; }

function RecordList({ module, records }: { module: ModuleKey; records: RecordRow[] }) { if (records.length === 0) return <div className="min-h-40 border-l-4 border-brand bg-canvas p-4"><p className="font-semibold text-ink">No records yet</p><p className="mt-1 text-sm leading-6 text-muted">Create your first {module === "documents" ? "private vault item" : "household record"} with the form.</p></div>; return <div className="space-y-2">{records.map((record) => <div key={String(record.id)} className="border-l-4 border-brand bg-canvas p-3"><p className="font-semibold text-sm text-ink">{String(record.title ?? record.name ?? record.display_name ?? record.file_name ?? "Household record")}</p><p className="mt-1 font-mono text-[10px] uppercase tracking-[0.1em] text-muted">{recordSummary(module, record)}</p></div>)}</div>; }
function recordSummary(module: ModuleKey, record: RecordRow) { if (module === "finance") return `${String(record.kind)} · ${String(record.amount)} ${String(record.currency)} · ${String(record.occurred_on)}`; if (module === "schedule") return new Date(String(record.starts_at)).toLocaleString(); if (module === "documents") return `${String(record.mime_type)} · ${String(record.byte_size)} bytes${record.linked_record ? ` · linked to ${String(record.linked_record)}` : " · no linked record"}`; if (module === "reminders") return `${String(record.kind)} · due ${new Date(String(record.due_at)).toLocaleString()}`; return String(record.category ?? record.relationship ?? "Household record"); }
