"use client";

import { useActionState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { createAsset, createFamilyPerson, createFinancialRecord, createReminder, createScheduleItem, initialModuleActionState, uploadDocument, type ModuleActionState } from "@/app/(workspace)/module-actions";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { FamilyAccessPanel, type HouseholdMemberView } from "@/components/family-access-panel";
import { summarizeFinanceRecords } from "@/lib/finance/summary";
import { getModuleSnapshot } from "@/lib/modules/summary";

export type ModuleKey = "family" | "finance" | "assets" | "schedule" | "documents" | "reminders";
type RecordRow = Record<string, unknown>;

const moduleMeta: Record<ModuleKey, { eyebrow: string; title: string; description: string }> = {
  family: { eyebrow: "People & membership", title: "Family records", description: "Keep profiles, relationships, and private membership operations in one household-scoped workspace." },
  finance: { eyebrow: "Income & expenses", title: "Financial records", description: "Log the household money movement that matters, with RLS-protected access." },
  assets: { eyebrow: "Home & valuables", title: "Assets", description: "Track household assets, values, and renewal points without exposing data outside the household." },
  schedule: { eyebrow: "Events & care", title: "Schedule", description: "Maintain appointments, care events, and household commitments in local time." },
  documents: { eyebrow: "Private storage", title: "Document vault", description: "Upload supported files to the private family bucket and retain searchable metadata." },
  reminders: { eyebrow: "Obligations", title: "Reminders", description: "Capture bills, renewals, appointments, birthdays, and other timely household obligations." },
};

export function ModuleWorkspace({ module, householdName, records, members = [], actorRole = "limited", searchQuery = "" }: { module: ModuleKey; householdName: string; records: RecordRow[]; members?: HouseholdMemberView[]; actorRole?: "owner" | "adult" | "limited"; searchQuery?: string }) {
  const meta = moduleMeta[module];
  const moduleSnapshot = getModuleSnapshot(module, records.length);
  const isFinance = module === "finance";
  return (
    <main className="container pb-32 pt-5 sm:py-10">
      <div className="border border-contrast bg-contrast p-5 text-white shadow-tactile sm:p-7"><p className="font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-white/65">{householdName} · {isFinance ? "Money center" : meta.eyebrow}</p><h1 className="mt-3 text-3xl font-black uppercase leading-[0.9] tracking-[-0.07em] sm:text-5xl">{isFinance ? "Household money" : meta.title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/70">{isFinance ? "Review recorded money movement first, then add one clear transaction. Entries remain household-scoped and transfers are never treated as income or spend." : meta.description}</p></div>
      {isFinance ? <FinanceOverview records={records} /> : null}
      {!isFinance ? <section className="mt-4 border border-line bg-surface p-4 shadow-tactile-sm sm:p-5" aria-label={`${meta.title} snapshot`}><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.15em] text-brand">{moduleSnapshot.label}</p><h2 className="mt-1 text-xl font-black uppercase tracking-[-0.05em]">{moduleSnapshot.countLabel}</h2></div><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">Household scoped</span></div><p className="mt-3 border-l-4 border-brand bg-soft p-3 text-sm leading-6 text-ink">{moduleSnapshot.guidance}</p><a href="#new-record" className="mt-4 inline-flex min-h-11 items-center border border-brand bg-brand px-4 text-sm font-bold text-white transition active:scale-[0.97]">{moduleSnapshot.primaryAction}</a></section> : null}
      <section className="mt-5 grid gap-5 lg:grid-cols-[0.85fr_1.15fr]"><Card id={isFinance ? "new-transaction" : "new-record"} className="order-2 lg:order-1"><CardHeader><p className="font-mono text-[10px] font-bold uppercase tracking-[0.15em] text-brand">{isFinance ? "Transaction entry" : "New record"}</p><h2 className="mt-1 text-xl font-black uppercase tracking-[-0.05em]">{isFinance ? "Record a movement" : moduleSnapshot.primaryAction}</h2><p className="mt-2 text-sm leading-6 text-muted">{isFinance ? "Enter one clear movement at a time. Transfers remain separate from income and spend." : "Save one clear household record with the access controls of this workspace."}</p></CardHeader><CardContent><ModuleForm module={module} /></CardContent></Card><Card id={isFinance ? "ledger" : "records"} className="order-1 bg-soft lg:order-2"><CardHeader><p className="font-mono text-[10px] font-bold uppercase tracking-[0.15em] text-muted">Household data</p><h2 className="mt-1 text-xl font-black uppercase tracking-[-0.05em]">{isFinance ? "Transaction history" : "Recent records"}</h2></CardHeader><CardContent>{module === "documents" ? <DocumentSearch initialQuery={searchQuery} /> : null}<RecordList module={module} records={records} /></CardContent></Card></section>{module === "family" ? <FamilyAccessPanel members={members} actorRole={actorRole} /> : null}
    </main>
  );
}

function ModuleForm({ module }: { module: ModuleKey }) {
  const action = module === "family" ? createFamilyPerson : module === "finance" ? createFinancialRecord : module === "assets" ? createAsset : module === "schedule" ? createScheduleItem : module === "documents" ? uploadDocument : createReminder;
  const [state, formAction, pending] = useActionState(action, initialModuleActionState);
  const router = useRouter();
  useEffect(() => { if (state.status === "success") router.refresh(); }, [router, state.status]);
  return <form action={formAction} className="grid gap-3" encType={module === "documents" ? "multipart/form-data" : undefined}>{module === "family" ? <FamilyFields /> : module === "finance" ? <FinanceFields /> : module === "assets" ? <AssetFields /> : module === "schedule" ? <ScheduleFields /> : module === "documents" ? <DocumentFields /> : <ReminderFields />}<ActionNotice state={state} /><Button type="submit" size="touch" disabled={pending}>{pending ? "Saving" : submitLabel(module)}</Button></form>;
}

function Label({ name, children }: { name: string; children: React.ReactNode }) { return <label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">{children}</span><Input name={name} required /></label>; }
function FamilyFields() { return <><Label name="displayName">Name</Label><Label name="relationship">Relationship</Label><label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">Birth date</span><Input name="birthDate" type="date" /></label></>; }
function FinanceFields() { return <><label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">Record type</span><select name="kind" className="min-h-12 border border-line bg-canvas px-3 text-sm outline-none focus:border-brand focus:ring-2 focus:ring-brand/25"><option value="expense">Expense</option><option value="income">Income</option><option value="transfer">Transfer</option><option value="liability">Liability</option></select></label><Label name="title">What is this movement?</Label><div className="grid grid-cols-2 gap-3"><label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">Amount</span><Input name="amount" type="number" min="0" step="0.01" inputMode="decimal" required /></label><label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">Currency</span><Input name="currency" defaultValue="USD" maxLength={3} autoCapitalize="characters" required /></label></div><label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">Date</span><Input name="occurredOn" type="date" required /></label><Label name="category">Category</Label></>; }
function AssetFields() { return <><Label name="name">Asset name</Label><Label name="category">Category</Label><div className="grid grid-cols-2 gap-3"><Label name="estimatedValue">Estimated value</Label><Label name="currency">Currency</Label></div><label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">Renewal date</span><Input name="renewalDueAt" type="datetime-local" /></label></>; }
function ScheduleFields() { return <><Label name="title">Event title</Label><Label name="category">Category</Label><label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">Starts</span><Input name="startsAt" type="datetime-local" required /></label><label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">Ends</span><Input name="endsAt" type="datetime-local" /></label></>; }
function DocumentFields() { return <><label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">File</span><Input name="file" type="file" accept="application/pdf,image/jpeg,image/png,text/plain" required /></label><Label name="label">Label</Label><Label name="relatedType">Related record type (optional)</Label><Label name="relatedId">Related record ID (optional)</Label><p className="text-xs leading-5 text-muted">PDF, JPEG, PNG, or text file; maximum 50 MB. File bytes stay in the private family bucket, while metadata is searchable and may link to a family record.</p></>; }
function ReminderFields() { return <><label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">Reminder type</span><select name="kind" className="h-11 border border-line bg-canvas px-3 text-sm outline-none focus:border-brand focus:ring-2 focus:ring-brand/25"><option value="bill">Bill</option><option value="renewal">Renewal</option><option value="appointment">Appointment</option><option value="birthday">Birthday</option><option value="custom">Custom</option></select></label><Label name="title">Title</Label><label className="grid gap-1"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">Due</span><Input name="dueAt" type="datetime-local" required /></label><Label name="leadTimeMinutes">Lead time in minutes</Label></>; }
function ActionNotice({ state }: { state: ModuleActionState }) { return state.status === "idle" ? null : <p role="status" className={state.status === "error" ? "text-sm font-medium text-error" : "text-sm font-medium text-ink"}>{state.message}{state.shareCode ? <><br /><code className="mt-2 inline-block select-all border border-line bg-soft px-2 py-1 text-xs text-ink">{state.shareCode}</code></> : null}</p>; }
function DocumentSearch({ initialQuery }: { initialQuery: string }) { return <form action="/documents" className="mb-4 flex gap-2"><Input name="q" defaultValue={initialQuery} placeholder="Search file name or label" aria-label="Search private documents" /><Button type="submit" size="compact">Search</Button></form>; }

function RecordList({ module, records }: { module: ModuleKey; records: RecordRow[] }) { if (records.length === 0) return <div className="min-h-40 border-l-4 border-brand bg-canvas p-4"><p className="font-semibold text-ink">{getModuleSnapshot(module, 0).emptyTitle}</p><p className="mt-1 text-sm leading-6 text-muted">Add the first household record when it becomes useful. This workspace remains private to the active household.</p><a href={module === "finance" ? "#new-transaction" : "#new-record"} className="mt-4 inline-flex min-h-11 items-center border border-brand bg-brand px-4 text-sm font-bold text-white transition active:scale-[0.97]">{getModuleSnapshot(module, 0).primaryAction}</a></div>; if (module === "finance") return <div className="space-y-2">{records.map((record) => <div key={String(record.id)} className="border-l-4 border-brand bg-canvas p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-sm text-ink">{String(record.title ?? "Financial record")}</p><p className="mt-1 font-mono text-[10px] uppercase tracking-[0.1em] text-muted">{String(record.kind)} · {String(record.occurred_on)}</p></div><p className={record.kind === "income" ? "shrink-0 text-right font-mono text-sm font-bold text-brand" : record.kind === "expense" || record.kind === "liability" ? "shrink-0 text-right font-mono text-sm font-bold text-error" : "shrink-0 text-right font-mono text-sm font-bold text-ink"}>{record.kind === "income" ? "+" : record.kind === "expense" || record.kind === "liability" ? "−" : ""}{formatMoney(Number(record.amount), String(record.currency ?? "USD"))}</p></div></div>)}</div>; return <div className="space-y-2">{records.map((record) => <div key={String(record.id)} className="border-l-4 border-brand bg-canvas p-3"><p className="font-semibold text-sm text-ink">{String(record.title ?? record.name ?? record.display_name ?? record.file_name ?? "Household record")}</p><p className="mt-1 font-mono text-[10px] uppercase tracking-[0.1em] text-muted">{recordSummary(module, record)}</p></div>)}</div>; }
function recordSummary(module: ModuleKey, record: RecordRow) { if (module === "finance") return `${String(record.kind)} · ${String(record.amount)} ${String(record.currency)} · ${String(record.occurred_on)}`; if (module === "schedule") return new Date(String(record.starts_at)).toLocaleString(); if (module === "documents") return `${String(record.mime_type)} · ${String(record.byte_size)} bytes${record.linked_record ? ` · linked to ${String(record.linked_record)}` : " · no linked record"}`; if (module === "reminders") return `${String(record.kind)} · due ${new Date(String(record.due_at)).toLocaleString()}`; return String(record.category ?? record.relationship ?? "Household record"); }

function FinanceOverview({ records }: { records: RecordRow[] }) { const summary = summarizeFinanceRecords(records); return <section className="mt-4 border border-line bg-surface p-4 shadow-tactile-sm sm:p-5" aria-label="Financial summary"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.15em] text-brand">Money snapshot</p><h2 className="mt-1 text-xl font-black uppercase tracking-[-0.05em]">Recorded position</h2></div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.12em] text-muted">{summary.recordCount} entries</p></div>{summary.hasMultipleCurrencies ? <p className="mt-4 border-l-4 border-brand bg-soft p-3 text-sm leading-6 text-ink">Records use more than one currency, so totals are intentionally not combined. Review each entry in its recorded currency.</p> : <><div className="mt-4 border border-contrast bg-contrast p-4 text-white"><p className="font-mono text-[10px] font-bold uppercase tracking-[0.14em] text-white/65">Net recorded position</p><p className="mt-2 text-3xl font-black tracking-[-0.07em]">{formatMoney(summary.netPosition ?? 0, summary.currency ?? "USD")}</p><p className="mt-2 text-xs leading-5 text-white/65">Recorded income minus expenses and liabilities. This is not a bank-account balance or forecast.</p></div><div className="mt-3 grid grid-cols-3 gap-2"><FinanceMetric label="In" value={formatMoney(summary.income ?? 0, summary.currency ?? "USD")} /><FinanceMetric label="Out" value={formatMoney(summary.expenses ?? 0, summary.currency ?? "USD")} /><FinanceMetric label="Owed" value={formatMoney(summary.liabilities ?? 0, summary.currency ?? "USD")} /></div></>}<div className="mt-4 grid grid-cols-2 gap-2"><a href="#new-transaction" className="flex min-h-11 items-center justify-center border border-brand bg-brand px-3 text-center text-sm font-bold text-white transition active:scale-[0.97]">Record transaction</a><a href="#ledger" className="flex min-h-11 items-center justify-center border border-line bg-canvas px-3 text-center text-sm font-bold text-ink transition hover:border-brand hover:text-brand active:scale-[0.97]">View ledger</a></div></section>; }
function FinanceMetric({ label, value }: { label: string; value: string }) { return <div className="border border-line bg-canvas p-3"><p className="font-mono text-[9px] font-bold uppercase tracking-[0.1em] text-muted">{label}</p><p className="mt-2 text-base font-black tracking-[-0.05em] text-ink sm:text-xl">{value}</p></div>; }
function submitLabel(module: ModuleKey) { if (module === "finance") return "Save transaction"; if (module === "family") return "Save person"; if (module === "assets") return "Save asset"; if (module === "schedule") return "Save event"; if (module === "documents") return "Upload private file"; return "Save reminder"; }
function formatMoney(value: number, currency: string) { try { return new Intl.NumberFormat("en", { style: "currency", currency, maximumFractionDigits: 2 }).format(Number.isFinite(value) ? value : 0); } catch { return `${Number.isFinite(value) ? value : 0} ${currency}`; } }
